/* groovylint-disable CompileStatic, NestedBlockDepth, VariableTypeRequired */

def changedEggFiles = [] as LinkedList<String>
def eggConfigs = [] as LinkedList<Map>
def PELICAN_USER_ID = 0

pipeline {
    agent any

    parameters { 
        string(name: 'PELICAN_BASE_URL', defaultValue: 'https://pelican.nussi.net/api/application', description: '')
        string(name: 'PELICAN_USER', defaultValue: '', description: '')
        password(name: 'PELICAN_TOKEN', defaultValue: '', description: 'Enter a password')
    }

    stages {
        stage('Resolve pelican user') {
            steps {
                script {
                    if (params.PELICAN_USER?.trim()?.length() == 0) {
                        error 'PELICAN_USER parameter is required'
                    }
                    if (params.PELICAN_TOKEN?.trim()?.length() == 0) {
                        error 'PELICAN_TOKEN parameter is required'
                    }

                    def response = httpRequest url: "${params.PELICAN_BASE_URL}/users", acceptType: 'APPLICATION_JSON', httpMode: 'GET'

                    echo response
                }
            }
        }

        stage('Detect egg changes') {
            steps {
                script {
                    def targetBranch = env.CHANGE_TARGET ?: 'main'
                    echo "Comparing changes against branch: origin/${targetBranch}"

                    sh 'git show-ref'

                    def eggsConfig = readJSON file: '.jenkins/eggs.json'

                    changedEggFiles = []
                    eggConfigs += eggsConfig['eggs']

                    eggConfigs.each { eggConfig ->
                        echo "Found egg configuration: ${eggConfig}"

                        String currentChangedEggDiffs = sh(
                            script: "git diff --name-only origin/${targetBranch} -- ${eggConfig['path']}",
                            returnStdout: true
                        )
                        .trim()

                        if (currentChangedEggDiffs.isEmpty() == false) {
                            def currentChangedEggFiles = currentChangedEggDiffs
                                .split('\n')
                                .findAll { file -> file.endsWith('.json') }
                                //.findAll { file -> file.endsWith('.json') && fileExists(file) }

                            echo "Detected ${currentChangedEggFiles.size()} changed egg files in path: ${eggConfig['path']}"

                            changedEggFiles += currentChangedEggFiles
                        } else {
                            echo "No changes detected in egg path: ${eggConfig['path']}"
                        }
                    }

                    echo 'Changed egg file:'
                    changedEggFiles.each { changedEggFile ->
                        echo changedEggFile
                    }
                }
            }
        }

        stage('Process changed egg files') {
            when {
                expression { return changedEggFiles.size() > 0 }
            }
            steps {
                script {
                    def parallelStages = [:]
                    for (int pi = 0; pi < changedEggFiles.size(); pi++) {
                        def fileToProcess = changedEggFiles[pi]
                        // create a closure that will be executed in parallel
                        parallelStages["Process ${fileToProcess}"] = {
                            node {
                                stage("Process ${fileToProcess}") {
                                    echo "Processing egg file: ${fileToProcess}"
                                }
                            }
                        }
                    }

                    if (parallelStages.size() > 0) {
                        parallel parallelStages
                    }
                }
            }
        }
    }
}
