/* groovylint-disable CompileStatic, NestedBlockDepth, VariableTypeRequired */

def hatchFileDescriptions = []
def hatchStages = [:]

pipeline {
    agent any

    environment {
        PELICAN_BASE_URL = credentials('jenkins-pelican-base-url')
        PELICAN_USER_ID = credentials('jenkins-pelican-user-id')
        PELICAN_TOKEN = credentials('jenkins-pelican-token')
    }

    stages {
        stage('Validate environment variables') {
            steps {
                script {
                    if (PELICAN_BASE_URL?.trim()?.length() == 0) {
                        error 'PELICAN_BASE_URL parameter is required'
                    }
                    if (PELICAN_USER_ID?.trim()?.length() == 0) {
                        error 'PELICAN_USER_ID parameter is required'
                    }
                    if (PELICAN_TOKEN?.trim()?.length() == 0) {
                        error 'PELICAN_TOKEN parameter is required'

                    }
                }
            }
        }

        stage('Scan for configs') {
            steps {
                script {
                    hatchFileDescriptions = findFiles(glob: "**/*.hatch.json")
                }
            }
        }

        stage('Hatching Egg\'s') {
            steps {
                script {
                    for (def hatchFileDescription : hatchFileDescriptions) {
                        def hatchFile = hatchFileDescription.path
                        hatchStages["Hatching Egg ${hatchFile}"] = hatchEgg(hatchFile)
                    }
                    parallel hatchStages
                }
            }
        }

//        stage('Detect egg changes') {
//            steps {
//                script {
//                    def targetBranch = env.CHANGE_TARGET ?: 'main'
//                    echo "Comparing changes against branch: origin/${targetBranch}"
//
//                    sh 'git show-ref'
//
//                    def eggsConfig = readJSON file: '.jenkins/eggs.json'
//
//                    changedEggFiles = []
//                    eggConfigs += eggsConfig['eggs']
//
//                    eggConfigs.each { eggConfig ->
//                        echo "Found egg configuration: ${eggConfig}"
//
//                        String currentChangedEggDiffs = sh(
//                            script: "git diff --name-only origin/${targetBranch} -- ${eggConfig['path']}",
//                            returnStdout: true
//                        )
//                        .trim()
//
//                        if (!currentChangedEggDiffs.isEmpty()) {
//                            def currentChangedEggFiles = currentChangedEggDiffs
//                                .split('\n')
//                                .findAll { file -> file.endsWith('.json') }
//                                //.findAll { file -> file.endsWith('.json') && fileExists(file) }
//
//                            echo "Detected ${currentChangedEggFiles.size()} changed egg files in path: ${eggConfig['path']}"
//
//                            changedEggFiles += currentChangedEggFiles
//                        } else {
//                            echo "No changes detected in egg path: ${eggConfig['path']}"
//                        }
//                    }
//
//                    echo 'Changed egg file:'
//                    changedEggFiles.each { changedEggFile ->
//                        echo changedEggFile
//                    }
//                }
//            }
//        }
//
//        stage('Testing egg\'s'){
//            steps {
//                script {
//                    for (int pi = 0; pi < changedEggFiles.size(); pi++) {
//                        String eggFile = changedEggFiles[pi]
//                        eggTestingStages["Testing Egg ${eggFile}"] = testEgg(eggFile, eggIds, PELICAN_USER.id as Integer)
//                        break //for testing only
//                    }
//                    parallel eggTestingStages
//                }
//            }
//        }
    }
}


def hatchEgg(def hatchFile, def pelicanUser) {
    def eggFile = hatchFile.replace('.hatch.json', '.json')
    def hatch = [:]
    def egg = [:]
    def server = [:]

    return {
        stage("Hatching Egg ${hatchFile}") {

            stage("Checking hatch file") {
                echo "Checking if hatch file '${hatchFile}' exists and is valid..."
                script {
                    catchError(message : "Hatch file failed validation ${hatchFile}".toString(), buildResult: 'UNSTABLE', stageResult: 'NOT_BUILT', catchInterruptions: false) {
                        if(!fileExists(hatchFile)) error("Hatch file was not found '${hatchFile}'")
                        hatch = readJSON(file: hatchFile)
                        echo "Hatch file '${hatchFile}' exsists and is valid!"
                    }
                }
            }

            stage("Checking egg file") {
                echo "Checking if egg file '${eggFile}' exists and is valid..."
                script {

                    catchError(message : "Egg file failed validation ${eggFile}".toString(), buildResult: 'UNSTABLE', stageResult: 'NOT_BUILT', catchInterruptions: false) {
                        if(!fileExists(eggFile)) error("Found egg file but no egg: ${eggFile}")
                        egg = readJSON(file: eggFile)
                        echo "Egg file '${eggFile}' exsists and is valid!"
                    }
                }
            }

            stage("Mark egg") {
                script {
                    catchError(message : "Failed to save egg ${eggFile}".toString(), buildResult: 'FAILURE', stageResult: 'FAILURE', catchInterruptions: false) {
                        String gitUUID = env.GIT_COMMIT as String
                        String fileUUID = eggFile
                        egg['uuid'] = UUID.nameUUIDFromBytes((fileUUID + '@' + gitUUID).getBytes()).toString()
                        writeJSON(file: eggFile, json: egg, pretty: 4)
                        echo "Set egg '${eggFile}' uuid to ${egg['uuid']}"
                    }
                }
            }

            stage("Importing egg") {
                echo "Importing egg file into the pelican panel: ${eggFile}"
                script {
                    catchError(message : "Failed to import egg ${eggFile}".toString(), buildResult: 'FAILURE', stageResult: 'FAILURE', catchInterruptions: false) {
                        def response = httpRequest url: "${env.PELICAN_BASE_URL}/eggs/import?format=json".toString(),
                                acceptType: 'APPLICATION_JSON',
                                contentType: 'APPLICATION_JSON',
                                httpMode: 'POST',
                                requestBody: (writeJSON(json: egg, returnText: true, pretty: 4) as String),
                                validResponseCodes: '200:299',
                                consoleLogResponseBody: false,
                                customHeaders: [[name: 'Authorization', value: "Bearer ${env.PELICAN_TOKEN}"]]
                        def body = readJSON text: response.content
                        egg['id'] = body['attributes']['id'] as int
                        echo "Successfully imported egg '${eggFile}' into the pelican panel with id: ${egg['id']}"
                    }
                }
            }

            stage("Creating server") {
                script {

                    server['name']="Jenkins ${env.JOB_BASE_NAME} ${env.BUILD_NUMBER}".toString()
                    server['external_id']=egg['uuid']
                    server['description']="Automated test server. Created by ${env.BUILD_URL}".toString()
                    server['user'] = pelicanUser as Integer
                    server['egg'] = egg['id']
                    server['environment'] = hatch['environment']
                    server['skip_scripts'] = false
                    server['oom_killer'] = false
                    server['limits']['memory'] = 10240
                    server['limits']['swap'] = -1
                    server['limits']['disk'] = 10240
                    server['limits']['io'] = 1000
                    server['limits']['cpu'] = 8000
                    server['feature_limits']['databases'] = 0
                    server['feature_limits']['allocations'] = 0
                    server['feature_limits']['backups'] = 0
                    server['deploy']['tags'] = ['jenkins']
                    def port_range = []
                    for (port in 25600..<25700) {
                        port_range.add(port)
                    }
                    server['deploy']['port_range']=port_range

                }
                echo "Creating server from egg: ${eggFile}"
                script {
                    catchError(message : "Failed to create server ${eggFile}".toString(), buildResult: 'FAILURE', stageResult: 'FAILURE', catchInterruptions: false) {
                        def response = httpRequest url: "${env.PELICAN_BASE_URL}/servers".toString(),
                                acceptType: 'APPLICATION_JSON',
                                contentType: 'APPLICATION_JSON',
                                httpMode: 'POST',
                                requestBody: (writeJSON(json: server, returnText: true, pretty: 4) as String),
                                validResponseCodes: '200:299',
                                consoleLogResponseBody: false,
                                customHeaders: [[name: 'Authorization', value: "Bearer ${env.PELICAN_TOKEN}"]]
                        def body = readJSON text: response.content
                        server['id'] = body['attributes']['id'] as int
                        echo "Successfully created server '${eggFile}' with id: ${server['id']}"
                    }
                }
            }


            stage("Deleting egg") {
                echo "Deleting egg ${egg['uuid']} '${eggFile}'"
                script {
                    catchError(message : "Failed to delete egg ${egg['uuid']} ${eggFile}".toString(), buildResult: 'SUCCESS', stageResult: 'NOT_BUILT', catchInterruptions: false) {
                        httpRequest url: "${env.PELICAN_BASE_URL}/eggs/${egg['uuid']}/uuid".toString(),
                                acceptType: 'APPLICATION_JSON',
                                contentType: 'APPLICATION_JSON',
                                httpMode: 'DELETE',
                                validResponseCodes: '200:299',
                                consoleLogResponseBody: false,
                                customHeaders: [[name: 'Authorization', value: "Bearer ${env.PELICAN_TOKEN}"]]
                        echo "Successfully deleted egg ${eggFile}"
                    }
                }
            }

        }
    }
}



//                    {
//                      "external_id": "${eggUUID}",
//                      "name": "Jenkins CI/CD - ${eggUUID}",
//                      "description": "${env.BUILD_NUMBER}",
//                      "user": ${userId},
//                      "egg": ${eggIds[eggFile]},
//                      "environment": [],
//                      "skip_scripts": false,
//                      "oom_killer": false,
//                      "start_on_completion": true,
//                      "limits": {
//                        "memory": 10240,
//                        "disk": 10240,
//                        "swap": -1,
//                        "io": 1000,
//                        "cpu": 800
//                      },
//                      "feature_limits": {
//                        "databases": 0,
//                        "allocations": 0,
//                        "backups": 0
//                      },
//                      "allocation": {},
//                      "deploy": {
//                        "locations": [],
//                        "tags": [
//                          "jenkins"
//                        ],
//                        "dedicated_ip": false,
//                        "port_range": [
//                            "25600","25601","25602","25603","25604",
//                            "25605","25606","25607","25608","25609",
//                            "25610","25611","25612","25613","25614",
//                            "25615","25616","25617","25618","25619",
//                            "25620","25621","25622","25623","25624",
//                            "25625","25626","25627","25628","25629",
//                            "25630","25631","25632","25633","25634",
//                            "25635","25636","25637","25638","25639",
//                            "25640","25641","25642","25643","25644",
//                            "25645","25646","25647","25648","25649",
//                            "25650","25651","25652","25653","25654",
//                            "25655","25656","25657","25658","25659",
//                            "25660","25661","25662","25663","25664",
//                            "25665","25666","25667","25668","25669"
//                        ]
//                      }
//                    }
//                    echo serverJson
//
//
//
//                    def response = httpRequest url: "${env.PELICAN_BASE_URL}/servers",
//                            acceptType: 'APPLICATION_JSON',
//                            contentType: 'APPLICATION_JSON',
//                            httpMode: 'POST',
//                            requestBody: serverJson,
//                            validResponseCodes: '0:499',
//                            customHeaders: [[name: 'Authorization', value: "Bearer ${env.PELICAN_TOKEN}"]]
//
//                    if(response.status >= 200 && response.status < 400) {
//                        def responseJson = readJSON text: response.content
//                        def serverId = responseJson['attributes']['id']
//
//                        echo "Successfully created server ${serverId} ${eggFile}"
//
//                    } else {
//                        def responseText = response.content
//
//                        echo "Failed to create server ${eggFile}, response code: ${response}"
//                        echo "Failure Response:\n${responseText}"
//
//                        error "Failed to create server ${eggFile}, response code: ${response}"
//                    }
//
//
//                }
//            }
//
